version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/press-release-app
hooks:
  ApplicationStop:
    - location: scripts/stop_containers.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_containers.sh
      timeout: 300
      runas: root