version: 0.2

phases:
  install:
    commands:
      - cd webapp/frontend/react
      - npm install
  build:
    commands:
      - cd webapp/frontend/react
      - npm run build

artifacts:
  secondary-artifacts:
    FrontendArtifact:
      base-directory: webapp/frontend/react/dist  # Viteならdist、CRAならbuild
      files:
        - '**/*'
    BackendArtifact:
      base-directory: webapp
      files:
        - '**/*'